name: Check Links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    environment:
      name: main
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check links
      uses: byrnereese/github-action-mkdocs-link-check@main
      with:
        file-extension: '.md'
        verbose-mode: 'yes'
        folder-path: 'docs'
        synchronous: 'yes'
        local-only: 'no'
        recurse: 'yes'
        excludes: 'assets'